### ISSUE TITLE
Support Bash autocompletion

### ISSUE THREAD

**Issue by mbrodala** [stylemistake/bash-task-runner#11]
It would be nice if the `runner` command had autocompletion for task names. This can be achieved easily with Bash completions.

To get the list of defined tasks we'd need a command like `runner tasks` which could then not be used anymore by 3rd party code (e.g. with a `task_tasks` function).

Opinions?

**Comment by stylemistake** [comment]
I'd use a flag for this, e.g. `runner -l`, because of the reason you've mentioned. And yes, this is a very useful feature!

**Comment by stylemistake** [comment]
I'm not sure about only one thing: whether it should be in `src/cli.sh` (seems like a more logical choice) or `src/runner.sh` (self-contained runnerfiles will be able to use this feature).

One could include both `cli.sh` and `runner.sh` into a self-contained runnerfile, but I don't know what downsides this approach has except for having two files to carry around.

Then I would not be sure, whether to include `cli.sh` and `runner.sh` in `index.sh`.

[Hard decision](http://www.nowgamer.com/wp-content/uploads/2015/05/Life-Is-Strange%E2%84%A2_20260425003852.jpg)... :)

**Comment by mbrodala** [comment]
Great changes, I'll have a look.
