### ISSUE TITLE
Provide a custom runnerfile using a flag

### ISSUE THREAD

**Issue by stylemistake** [stylemistake/bash-task-runner#7]
Use file as a runnerfile:
`runner -f <file>`

**Comment by stylemistake** [comment]
@mbrodala I summon you to test this shit out. :)

I also cleaned up the pavement for you to implement the bash autocompletion.

**Comment by mbrodala** [comment]
I'll have a look. :-)

**Comment by mbrodala** [comment]
How is one supposed to execute the runner on CLI now? You've recently [dropped the `bin/runner` file](https://github.com/stylemistake/bash-task-runner/commit/13933b86b77814c57360977d90fd8fc9acfafeb2).

**Comment by mbrodala** [comment]
Overriding the runnerfile seems to work fine:

```
$ cat > foo.sh
task_foo() {
  echo "Foo"
}
$ bash bash-task-runner/index.sh -f foo.sh foo
[10:01:01.472] Starting 'foo'...
Foo
[10:01:01.478] Finished 'foo' after 2 ms
```

**Comment by stylemistake** [comment]
Ok, dropping `bin/runner` was a bad idea. :)
